// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc.team2509.robot.subsystems;

import org.usfirst.frc.team2509.robot.*;
import org.usfirst.frc.team2509.robot.subsystems.*;
import org.usfirst.frc.team2509.robot.commands.*;

import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.command.Subsystem;


public class Guides extends Subsystem {

    private final DoubleSolenoid piston = RobotMap.guideDoubleSolenoid;

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    
    public void In(){
    	piston.set(DoubleSolenoid.Value.kForward);
    }
    public void Out(){
    	piston.set(DoubleSolenoid.Value.kReverse);
    }
    public void Standby(){
    	piston.set(DoubleSolenoid.Value.kOff);
    }
}

