// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc.team2509.robot.subsystems;

import org.usfirst.frc.team2509.robot.RobotMap;
import org.usfirst.frc.team2509.robot.commands.RLiftStop;

import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.command.Subsystem;



public class RightLift extends Subsystem {

    private final DigitalInput Top = RobotMap.rightLiftLimitSwitchRT;
    private final DigitalInput Bottom = RobotMap.rightLiftLimitSwitchRB;
    private final SpeedController motor = RobotMap.rightLiftMotorR;

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
 
        setDefaultCommand(new RLiftStop());

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    public void Up(){
    	if((Top.get()&&Bottom.get()) == false){
    		motor.set(0.7);
    	}else{
    		Stop();
    	}
    }
    public void Down(){
    	if((Top.get()&&Bottom.get()) == false){
    		motor.set(-0.7);
    	}else{
    		Stop();
    	}
    }
    public void Stop(){
    	motor.set(0);
    }
}

